---
title: "Research vs. Reality"
format: html
---
## Why isn't research implemented in organizations more often?

A year ago, I took a course on personnel psychology (also known as industrial psychology). That course was mostly about hiring practices and methods of measuring people's work performance. The professor would talk quite a bit about cool hiring methods outside of the standard job interview. An example being a practical test, where applicants would perform job tasks and would be rated on how well they did. This seems like an interesting method of comparing applicants that wouldn't encourage deceptive behavior from said applicants (such is the case with interviews). However, I have rarely seen in the workforce. This is what made me think about the relationship between organizations and research related to them. 

This seems to be a common issue in the field of I/O (industrial/organizational) psychology, where organizations have access to knowledge on effective practices, yet don't implement it. In many cases, the proposed changes are found to increase productivity from employees. Such is the case with the 4 day work week. [Research](https://commons.erau.edu/cgi/viewcontent.cgi?article=1023&context=ww-research-methods-rsch202) consistently shows that implementing a 4 day work week improves many different things, chief among them being gross domestic product. Being less restrictive on employees benefits organizations, yet these changes are often tossed aside. 

Money isn't really a factor in this since the 4-day work week *increases* the amount that organizations can obtain. One explanation therefore is that the people in charge of businesses are incompetent. Another explanation is that business leaders desire more power over employees, or at least the feeling that they have power over employees. The third explanation is ignorance. Information about better practices is available, however, many people don't know how to search for them or are too busy doing other things to search for them. Information is only useful if it is known, after all. It would be hard to label one explanation as the correct one due to every organization being different. 